---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: generate locales
      locale_gen: name=en_US.UTF-8 state=present
      when: ansible_distribution=='Debian' or ansible_distribution=='Ubuntu'
