---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: update the apt cache
      apt: >
        update_cache=yes
        cache_valid_time=300
      register: apt_update
      when: ansible_distribution=='Debian' or ansible_distribution=='Ubuntu'

    - name: upgrade all packages
      apt:
        upgrade: dist
        dpkg_options: "force-confold,force-confdef,log=\
          /var/log/apt-upgrade_{{ ansible_date_time.date }}\
          -{{ ansible_date_time.time }}.log"
        cache_valid_time: 300
      register: apt_upgrade
      when: ansible_distribution=='Debian' or ansible_distribution=='Ubuntu'

    - name: install build-essential
      apt: name=build-essential state=present

    #  flex, bison and all others needed to build 'perf'
    - name: install build dependencies
      apt: name={{ item }} state=present
      with_items:
        - bc
        - vim
        - kernel-package
        - libncurses5-dev
        - curl
        - libssl-dev
        - flex
        - bison
        - git
        - python-dev
        - libaudit-dev
        - liblzma-dev
        - libelf-dev
        - libdw-dev
        - libslang2-dev
        - systemtap-sdt-dev
        - binutils-dev
        - libperl-dev
        - libnuma-dev

    - name: install libiberty on Jessie only
      apt: name=libiberty-dev
      when: ansible_distribution_release == 'Jessie'

    - name: create directory for kernel building
      file: path=/build state=directory
          owner=fx

    - name: fetch kernel source
      get_url:
        url: "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.tar.xz"
        dest: /build
        sha256sum: "029098dcffab74875e086ae970e38284\
          56838da6e0ba22ce3f64ef764f3d7f1a"
        timeout: 20
        owner: fx
      register: kernel_fetch

    - name: unpack the kernel source
      shell: tar xf linux-4.9.tar.xz
      args:
        chdir: /build
        creates: linux-4.9
      when: kernel_fetch|changed
