---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: install build-essential
      apt: name=build-essential state=present

    #  flex, bison and all others needed to build 'perf'
    - name: install build dependencies
      apt: name={{item}} state=present
      with_items:
        - bc
        - vim
        - kernel-package
        - libncurses5-dev
        - curl
        - libssl-dev
        - flex
        - bison
        - git
        - python-dev
        - libaudit-dev
        - liblzma-dev
        - libelf-dev
        - libdw-dev
        - libslang2-dev
        - systemtap-sdt-dev
        - binutils-dev
        - libperl-dev 
        - libnuma-dev

    - name: install libiberty on Jessie only
      apt: name=libiberty-dev
      when: ansible_distribution_release == 'Jessie'

    - name: create directory for kernel building
      file: path=/build state=directory
          owner=fx
    
    - name: fetch kernel source
      get_url: url=https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.8.11.tar.xz
              dest=/build
              sha256sum=cc0f42f408ba3e51f8b0e93e3d8050ff18569456d286cb2a1aca3327dd06890f
              timeout=20
              owner=fx
      register: kernel_fetch

    - name: unpack the kernel source
      shell: tar xf linux-4.8.11.tar.xz
      args:
        chdir: /build
        creates: linux-4.8.11
      when: kernel_fetch|changed
