---
#
# Install Telegraf package
#
- hosts: all
  gather_facts: yes
  become: yes
  tasks:

  - group: name=telegraf state=present
  - user: name=telegraf comment="Telegraf" group=telegraf
  - file: path=/opt/telegraf state=directory mode=0755 owner=telegraf group=telegraf

  - name: check if telegraf is telegraf_installed
    shell: dpkg -l |grep -c telegraf
    register: telegraf_installed
    ignore_errors: True

  - name: Fetch Telegraf package
    get_url: >
      url=http://get.influxdb.org/telegraf/telegraf_0.12.1-1_amd64.deb
      dest=/tmp
      sha256sum=275d06f2a8418135c2710a9b8235a1738a1bf9dcd442ba44f7215c55fe591a75
    when: telegraf_installed.stdout == '0' and ansible_architecture == "x86_64"
    register: telegraf_fetch
  
  - name: Fetch Telegraf package
    get_url: >
      url=http://get.influxdb.org/telegraf/telegraf_0.12.1-1_armhf.deb
      dest=/tmp
      sha256sum=ec9bd0d59d4dad44f18c2c4b6c99b433c7c0c9bf08e6f1178390255ab00d9372
    when: telegraf_installed.stdout == '0' and ansible_architecture == "armv7l"
    register: telegraf_fetch

  - name: Fetch sockstat.py
    get_url: >
      url=https://raw.githubusercontent.com/fxlv/monitoring/master/scripts/sockstat.py
      dest=/opt/telegraf
      sha256sum=65fc3c023d113ef8d6f6a00aaf9e3827e2f3635abbde492c790307992349c097

  - name: set proper permissions for sockstat.py
    file: path=/opt/telegraf/sockstat.py
          owner=root group=root mode=0755

  - name: Fetch files.py
    get_url: >
      url=https://raw.githubusercontent.com/fxlv/monitoring/master/scripts/files.py
      dest=/opt/telegraf
      sha256sum=1c5f5112d2b7ad21b219d2a429f6079f250425b28f21cadae9eca56fa140c1f9

  - name: set proper permissions for files.py
    file: path=/opt/telegraf/files.py
          owner=root group=root mode=0755

  - name: install Telegraf
    apt: deb=/tmp/telegraf_0.12.1-1_amd64.deb
    when: telegraf_installed.stdout == '0'
    register: telegraf_install
    when: ansible_architecture == "x86_64"
  
  - name: install Telegraf
    apt: deb=/tmp/telegraf_0.12.1-1_armhf.deb
    when: telegraf_installed.stdout == '0'
    register: telegraf_install
    when: ansible_architecture == "armv7l"

  - name: Configure Telegraf
    copy: src=templates/telegraf.conf
          dest=/etc/opt/telegraf/telegraf.conf
          owner=root group=root mode=644
    notify:
    - restart telegraf

  handlers:
  - name: restart telegraf
    service: name=telegraf state=restarted
