---
 - hosts: all
   gather_facts: yes
   sudo: yes
   tasks:

    - name: update the apt cache
      apt: update_cache=yes 
           cache_valid_time=300
      register: apt_update
      when: ansible_distribution=='Debian' or ansible_distribution=='Ubuntu'
    
    - name: install nagios agent and its components
      apt: name={{item}} state=present
      with_items:
         - nagios-nrpe-server
         - nagios-plugins

    - name: nagios sudoers file
      copy: src=templates/nrpe.cfg
            dest=/etc/nagios/nrpe.cfg
            owner=root group=root mode=644
      notify:
        - restart nagios-nrpe-server
        - tail syslog and grep for nrpe
        - print syslog
    
    - name: nagios sudoers file
      copy: src=templates/nagiosnrpe
            dest=/etc/sudoers.d/nagiosnrpe
            owner=root group=root mode=644

   handlers:
     - name: restart nagios-nrpe-server
       service: name=nagios-nrpe-server state=restarted
     - name: tail syslog and grep for nrpe
       shell: tail /var/log/syslog -n 50 | grep "nrpe\["
       register: nrpe_syslog
     - name: print syslog
       debug: var=nrpe_syslog.stdout_lines
