---
- hosts: all
  sudo: yes
  tasks:
    - shell: ls -d linux-headers*.deb
      args:
        chdir: /mnt/resource/build
      register: headers_package
    - name: fetch kernel headers
      fetch: >
        src=/mnt/resource/build/{{headers_package.stdout}}
        dest=/tmp/{{headers_package.stdout}} flat=yes
    - shell: ls -d linux-image*.deb
      args:
        chdir: /mnt/resource/build
      register: linux_image
    - name: fetch kernel
      fetch: >
        src=/mnt/resource/build/{{linux_image.stdout}}
        dest=/tmp/{{linux_image.stdout}} flat=yes
