---
- hosts: all
  tasks:
    - name: Install sysstat to ensure that sar commmand is available
      apt:
        name: sysstat
        state: present

    - name: check if and when sar data was last collected
      stat: 
        path: /tmp/data.sar
      register: sar_data_stat

    - name: collect SAR stats
      command: sar -o /tmp/data.sar 2 150
      async: 310
      poll: 5
      # check when was the stats file last modified and compare to current unix timestamp - 30 seconds
      # therefore we only collect stats if stats were last collected longer than 30 sec ago
      when: "ansible_date_time.epoch|int -30 > sar_data_stat.stat.mtime|int"
      notify: prep sar file

  handlers:
    - name: prep sar file
      shell: sar -A -f /tmp/data.sar > /tmp/data.sar.txt
      notify: fetch sar files
    - name: fetch sar files
      fetch:
        src: /tmp/data.sar.txt
        dest: /tmp/{{ ansible_hostname }}_{{ date }}_{{ hour }}-{{ minute }}-{{ second }}_data.sar.txt
        flat: yes
