---
- hosts: all
  become: yes
  tasks:
    - name: collect SAR stats
      shell: sar -o data.sar 2 300 chdir=/root
      environment: LC_ALL=C
      async: 510

    - name: prep sar file
      shell: sar -A -f data.sar > data.sar.txt chdir=/root
      environment: LC_ALL=C

    - name: fetch sar files
      fetch:
        src: /root/data.sar.txt
        dest: /tmp/{{ ansible_hostname }}-data.sar.txt
        flat: yes
