---
#
# Update a FreeBSD machine and its packages.
# This only works for 10.x as it does binary updates.
#
- hosts: all
  sudo: yes

  tasks:
    - name: Fetch any new FreeBSD updates
      shell: freebsd-update fetch 
      when: ansible_distribution == 'FreeBSD'
      register: result_update
      changed_when: "'No updates needed' not in result_update.stdout"

    - debug: var=result_update
      when: result_update.changed
    
    - name: Install FreeBSD updates
      shell: freebsd-update install
      when: ansible_distribution == 'FreeBSD' and result_update.changed
      register: result_update_install

    - debug: var=result_update_install
      when: result_update_install.changed
    
    - name: Upgrade FreeBSD packages
      shell: pkg upgrade
      when: ansible_distribution == 'FreeBSD'
      register: result_pkg
      changed_when: "'Your packages are up to date' not in result_pkg.stdout"

    - debug: var=result_pkg
      when: result_pkg.changed

