# On-Start automation to tell that HA is running
#- id: '1114971034062'
#  alias: HA started up
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service:
#      entity_id: light.desk
#      flash: short
#    - service:
#      entity_id: group.living_room_lights_ceiling
#      flash: short
# Living room lights on
- id: '1544978034062'
  alias: Living room switch ON
  trigger:
  - entity_id: sensor.hue_dimmer_switch_1
    platform: state
    to: 1_click_up
  condition: []
  action:
    
    - service: light.turn_on
      entity_id: light.balls
    
    - service: light.turn_on
      entity_id: light.living_room_balls
    
    - service: light.turn_on
      entity_id: light.desk
      data_template: 
        brightness: >
          {% if is_state('light.desk', 'off') %}
            {# If the light was completely off, set it to 70 #}
            70
            {% else %}
            {# If the light was ON, the set brightness depending on current brightness #}
            {% if states.light.desk.attributes.brightness < 70 %}
              70
              {% elif states.light.desk.attributes.brightness > 69 %}
              {% if states.light.desk.attributes.brightness < 140 %}
                140
                {% else %}
                255
              {% endif %}
            {% endif %}
          {% endif %}
          
        transition: 5
    
    - service: light.turn_on
      entity_id: light.stavlampa
      data: 
        brightness_pct: 50
        transition: 5

# Living room lights on, bright
- id: '1544978034061'
  alias: Living room switch ON, bright
  trigger:
  - entity_id: sensor.hue_dimmer_switch_1
    platform: state
    to: 1_hold_up
  condition: []
  action:
    
    - service: light.turn_on
      entity_id: light.balls
    
    - service: light.turn_on
      entity_id: light.living_room_balls
    
    - service: light.turn_on
      entity_id: light.desk
      data: 
        brightness_pct: 100
        transition: 2
    
    - service: light.turn_on
      entity_id: light.stavlampa
      data: 
        brightness_pct: 100
        transition: 2
# Living room lights off
- id: '1545593976803'
  alias: living room switch OFF
  trigger:
  - entity_id: sensor.hue_dimmer_switch_1
    platform: state
    to: 4_click_up
  condition: []
  action:
    - service: light.turn_off
      entity_id: group.living_room_lights_all

# Window lights only
- id: '1545827322660'
  alias: Window lights ON
  trigger:
  - entity_id: sensor.hue_dimmer_switch_1
    platform: state
    to: 2_click_up
  action:
  - service: light.turn_on
    data:
      entity_id: light.balls

# Ceiling lights only
- id: '1545827568411'
  alias: Ceiling lights ON
  trigger:
  - entity_id: sensor.hue_dimmer_switch_1
    platform: state
    to: 3_click_up
  action:
  - service: light.turn_on
    entity_id: light.living_room_1
    data: 
      brightness_pct: 50
  - service: light.turn_on
    entity_id: light.living_room_2
    data: 
      brightness_pct: 50

# Ceiling lights only, bright
- id: '1545827568479'
  alias: Ceiling lights ON, bright
  trigger:
  - entity_id: sensor.hue_dimmer_switch_1
    platform: state
    to: 3_hold_up
  action:
  - service: light.turn_on
    entity_id: light.living_room_1
    data: 
      brightness_pct: 100
  - service: light.turn_on
    entity_id: light.living_room_2
    data: 
      brightness_pct: 100

####################################################
# WC lights during daytime
####################################################
- id: '1546269349037'
  alias: wc motion during the day
  trigger:
  - entity_id: sensor.wc_motion_rest
    platform: state
    #from: False
    #to: True 
  action:
  - service: light.turn_on
    entity_id: group.wc
    data_template:
      brightness: >
        {% if states.sensor.nighttime.state == 'True' %}
        50
        {% else %}
        200
        {% endif %}   
      transition: 5


####################################################
# WC lights off (any time of the day, same automation)
####################################################

- id: wc_motion_off_day
  alias: wc_motion_off_day
  trigger:
  - entity_id: binary_sensor.hallway_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_off
    data:
      entity_id: group.wc
      transition: 10

####################################################
# Hallway lights
####################################################


- id: 'hallway_motion_day'
  alias: hallway motion during the day
  trigger:
  - entity_id: sensor.hallway_motion_rest
    platform: state
    #from: 'off'
    #to: 'on'
  action:
  # hallway entrance
  - service: light.turn_on
    entity_id: group.hallway_lights
    data_template:
      brightness: >
        {% if states.sensor.nighttime.state == 'True' %}
        50
        {% else %}
        200
        {% endif %}   
      transition: 5



- id: 'hallway_motion_off'
  alias: hallway motion off
  trigger:
  - entity_id: binary_sensor.hallway_above_kitchen_motion_door
    platform: state
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  action:
  - service: light.turn_off
    data:
      entity_id: group.hallway_lights
      transition: 10
