---
  - include: motd.yml
    when: ansible_os_family == "Debian"
  - include: locales.yml
    when: ansible_os_family == "Debian"
  - include: resolver.yml
    when: ansible_os_family == "Debian"
    
